In [1]:
import pandas as pd

### Merge Data Train

In [2]:
train_bodies_path = "./data/train/train_bodies.csv"
train_stances_path = "./data/train/train_stances.csv"

In [3]:
train_bodies = pd.read_csv(train_bodies_path)
train_bodies.head()

   Body ID                                        articleBody
0        0  A small meteorite crashed into a wooded area i...
1        4  Last week we hinted at what was to come as Ebo...
2        5  (NEWSER) – Wonder how long a Quarter Pounder w...
3        6  Posting photos of a gun-toting child online, I...
4        7  At least 25 suspected Boko Haram insurgents we...

In [4]:
train_stances = pd.read_csv(train_stances_path)
train_stances.head()

                                            Headline  Body ID     Stance
0  Police find mass graves with at least '15 bodi...      712  unrelated
1  Hundreds of Palestinians flee floods in Gaza a...      158      agree
2  Christian Bale passes on role of Steve Jobs, a...      137  unrelated
3  HBO and Apple in Talks for $15/Month Apple TV ...     1034  unrelated
4  Spider burrowed through tourist's stomach and ...     1923   disagree

In [5]:
data_train = pd.merge(train_bodies, train_stances, on="Body ID")
data_train.head()

,Body ID,articleBody,Headline,Stance
0,0,A small meteorite crashed into a wooded area i...,"Soldier shot, Parliament locked down after gun...",unrelated
1,0,A small meteorite crashed into a wooded area i...,Tourist dubbed ‘Spider Man’ after spider burro...,unrelated
2,0,A small meteorite crashed into a wooded area i...,Luke Somers 'killed in failed rescue attempt i...,unrelated
3,0,A small meteorite crashed into a wooded area i...,BREAKING: Soldier shot at War Memorial in Ottawa,unrelated
4,0,A small meteorite crashed into a wooded area i...,Giant 8ft 9in catfish weighing 19 stone caught...,unrelated

In [6]:
train_path = "./data/train/train.csv"

In [7]:
data_train.to_csv(train_path, index=False)

### Merge Data Test

In [8]:
test_bodies_path = "./data/test/test_bodies.csv"
test_stances_path = "./data/test/test_stances_unlabeled.csv"

In [9]:
test_bodies = pd.read_csv(test_bodies_path)
test_bodies.head()

   Body ID                                        articleBody
0        1  Al-Sisi has denied Israeli reports stating tha...
1        2  A bereaved Afghan mother took revenge on the T...
2        3  CNBC is reporting Tesla has chosen Nevada as t...
3       12  A 4-inch version of the iPhone 6 is said to be...
4       19  GR editor’s Note\r\n\r\nThere are no reports i...

In [10]:
test_stances = pd.read_csv(test_stances_path)
test_stances.head()

                                            Headline  Body ID
0  Ferguson riots: Pregnant woman loses eye after...     2008
1  Crazy Conservatives Are Sure a Gitmo Detainee ...     1550
2  A Russian Guy Says His Justin Bieber Ringtone ...        2
3  Zombie Cat: Buried Kitty Believed Dead, Meows ...     1793
4  Argentina's President Adopts Boy to End Werewo...       37

In [11]:
data_test = pd.merge(test_bodies, test_stances, on="Body ID")
data_test.head()

,Body ID,articleBody,Headline
0,1,Al-Sisi has denied Israeli reports stating tha...,Apple installing safes in-store to protect gol...
1,1,Al-Sisi has denied Israeli reports stating tha...,El-Sisi denies claims he'll give Sinai land to...
2,1,Al-Sisi has denied Israeli reports stating tha...,Apple to keep gold Watch Editions in special i...
3,1,Al-Sisi has denied Israeli reports stating tha...,Apple Stores to Keep Gold “Edition” Apple Watc...
4,1,Al-Sisi has denied Israeli reports stating tha...,South Korean woman's hair 'eaten' by robot vac...

In [12]:
test_path = "./data/test/test.csv"

In [ ]:
data_test.to_csv(test_path, index=False)

: